import './globals.css';

const siteUrl = 'https://kaveesh.cv';

export const metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Kaveesh Senevirathne — Software Engineer | Full Stack Developer | Cloud & AI',
    template: '%s | Kaveesh Senevirathne',
  },
  description:
    'Software Engineer with 4+ years of experience building scalable web applications, cloud microservices, and AI-integrated solutions. Expertise in Java, TypeScript, Spring Boot, React, Next.js, Angular, AWS, and modern AI tools. Currently at SeekaHost & ClickDo (UK).',
  keywords: [
    'Kaveesh Senevirathne',
    'Software Engineer',
    'Full Stack Developer',
    'Cloud Engineer',
    'AI Enthusiast',
    'Java Developer',
    'JavaScript',
    'TypeScript',
    'Spring Boot',
    'React',
    'Angular',
    'Next.js',
    'Node.js',
    'AWS',
    'Docker',
    'Python',
    'Machine Learning',
    'LangChain',
    'Microservices',
    'Sri Lanka',
    'UK',
    'Remote Developer',
    'SeekaHost',
    'ClickDo',
    'Portfolio',
    'Hire Developer',
  ],
  authors: [{ name: 'Kaveesh Senevirathne', url: siteUrl }],
  creator: 'Kaveesh Senevirathne',
  publisher: 'Kaveesh Senevirathne',
  category: 'technology',
  classification: 'Software Engineering Portfolio',
  openGraph: {
    type: 'profile',
    locale: 'en_US',
    url: siteUrl,
    siteName: 'Kaveesh Senevirathne — Portfolio',
    title: 'Kaveesh Senevirathne — Software Engineer | Full Stack Developer | Cloud & AI',
    description:
      'Software Engineer with 4+ years building scalable web apps, cloud microservices, and AI solutions. Expert in Java, TypeScript, React, Spring Boot, AWS. Currently at SeekaHost & ClickDo (UK).',
    // OG image auto-generated by app/opengraph-image.js
    firstName: 'Kaveesh',
    lastName: 'Senevirathne',
    username: 'KHSenevirathne',
    gender: 'male',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@KHSenevirathne',
    creator: '@KHSenevirathne',
    title: 'Kaveesh Senevirathne — Software Engineer | Full Stack Developer',
    description:
      'Software Engineer building scalable web apps, cloud microservices, and AI solutions. 4+ years experience with Java, TypeScript, React, Spring Boot, AWS.',
    // OG image auto-generated by app/opengraph-image.js
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: siteUrl,
  },
  verification: {
    // Add these when you have them:
    // google: 'your-google-verification-code',
    // yandex: 'your-yandex-verification-code',
    // bing: 'your-bing-verification-code',
  },
  other: {
    'msapplication-TileColor': '#0d1017',
    'theme-color': '#0d1017',
  },
};

// JSON-LD Structured Data
const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Kaveesh Senevirathne',
  alternateName: 'KH Senevirathne',
  url: siteUrl,
  image: `${siteUrl}/opengraph-image`,
  jobTitle: 'Software Engineer',
  description:
    'Full Stack Software Engineer with 4+ years of experience building scalable web applications, cloud microservices, and AI-integrated solutions.',
  email: 'mailto:khsenevirathne@gmail.com',
  telephone: '+94765350039',
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Galle',
    addressCountry: 'LK',
  },
  alumniOf: [
    {
      '@type': 'CollegeOrUniversity',
      name: 'London Metropolitan University',
      url: 'https://www.londonmet.ac.uk',
    },
    {
      '@type': 'EducationalOrganization',
      name: 'Institute of Software Engineering (IJSE)',
    },
  ],
  worksFor: [
    {
      '@type': 'Organization',
      name: 'SeekaHost',
      url: 'https://www.seekahost.com',
    },
    {
      '@type': 'Organization',
      name: 'ClickDo',
      url: 'https://www.clickdo.co.uk',
    },
  ],
  knowsAbout: [
    'Java', 'JavaScript', 'TypeScript', 'Python', 'C#', 'PHP',
    'Spring Boot', 'React', 'Angular', 'Next.js', 'Node.js', 'NestJS',
    'AWS', 'Docker', 'Microservices', 'CI/CD',
    'Machine Learning', 'TensorFlow', 'LangChain', 'OpenAI API',
    'MySQL', 'MongoDB', 'REST APIs',
    'Full Stack Development', 'Cloud Computing', 'DevOps',
  ],
  sameAs: [
    'https://www.linkedin.com/in/kaveesh-senevirathne',
    'https://github.com/KHSenevirathne',
    'https://stackoverflow.com/users/14956167/kaveesh-senevirathne',
    'https://twitter.com/KHSenevirathne',
  ],
};

const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Kaveesh Senevirathne Portfolio',
  url: siteUrl,
  description: 'Professional portfolio of Kaveesh Senevirathne — Software Engineer & Full Stack Developer',
  author: {
    '@type': 'Person',
    name: 'Kaveesh Senevirathne',
  },
  inLanguage: 'en',
};

const profilePageSchema = {
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  dateCreated: '2024-01-01',
  dateModified: new Date().toISOString().split('T')[0],
  mainEntity: {
    '@id': siteUrl,
    '@type': 'Person',
    name: 'Kaveesh Senevirathne',
  },
};

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Home',
      item: siteUrl,
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0d1017" />
        <meta name="color-scheme" content="dark" />

        {/* JSON-LD Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(profilePageSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
        />
      </head>
      <body className="min-h-screen">
        <div className="grain-overlay" aria-hidden="true" />
        {children}
      </body>
    </html>
  );
}
